/**
 * Deep Spot species catalog — 100 species (size-group spike sheet).
 * Generated by scripts/build-species-from-spike.py
 */
const CREATURE_TYPES = [
  {
    "id": "sardine",
    "emoji": "\ud83d\udc1f",
    "name": "Sardine",
    "rarity": "common",
    "points": 8,
    "minDepth": 0,
    "weight": 36
  },
  {
    "id": "shrimp",
    "emoji": "\ud83e\udd90",
    "name": "Reef Shrimp",
    "rarity": "common",
    "points": 8,
    "minDepth": 1,
    "weight": 36
  },
  {
    "id": "clownfish",
    "emoji": "\ud83d\udc20",
    "name": "Clownfish",
    "rarity": "common",
    "points": 9,
    "minDepth": 1,
    "weight": 35
  },
  {
    "id": "shell",
    "emoji": "\ud83d\udc1a",
    "name": "Queen Conch",
    "rarity": "common",
    "points": 9,
    "minDepth": 2,
    "weight": 35
  },
  {
    "id": "crab",
    "emoji": "\ud83e\udd80",
    "name": "Hermit Crab",
    "rarity": "common",
    "points": 9,
    "minDepth": 2,
    "weight": 35
  },
  {
    "id": "anchovy",
    "emoji": "\ud83d\udc1f",
    "name": "Anchovy",
    "rarity": "common",
    "points": 10,
    "minDepth": 3,
    "weight": 34
  },
  {
    "id": "silverside",
    "emoji": "\ud83d\udc1f",
    "name": "Silverside",
    "rarity": "common",
    "points": 10,
    "minDepth": 4,
    "weight": 34
  },
  {
    "id": "damselfish",
    "emoji": "\ud83d\udc20",
    "name": "Damselfish",
    "rarity": "common",
    "points": 10,
    "minDepth": 4,
    "weight": 34
  },
  {
    "id": "parrotfish",
    "emoji": "\ud83d\udc1f",
    "name": "Parrotfish",
    "rarity": "common",
    "points": 11,
    "minDepth": 5,
    "weight": 33
  },
  {
    "id": "butterflyfish",
    "emoji": "\ud83d\udc20",
    "name": "Butterflyfish",
    "rarity": "common",
    "points": 11,
    "minDepth": 5,
    "weight": 33
  },
  {
    "id": "blenny",
    "emoji": "\ud83d\udc1f",
    "name": "Blenny",
    "rarity": "common",
    "points": 11,
    "minDepth": 6,
    "weight": 33
  },
  {
    "id": "goby",
    "emoji": "\ud83d\udc1f",
    "name": "Goby",
    "rarity": "common",
    "points": 12,
    "minDepth": 6,
    "weight": 32
  },
  {
    "id": "seahorse",
    "emoji": "\ud83d\udc34",
    "name": "Seahorse",
    "rarity": "common",
    "points": 12,
    "minDepth": 7,
    "weight": 32
  },
  {
    "id": "pipefish",
    "emoji": "\ud83d\udc1f",
    "name": "Pipefish",
    "rarity": "common",
    "points": 12,
    "minDepth": 8,
    "weight": 32
  },
  {
    "id": "starfish",
    "emoji": "\u2b50",
    "name": "Sea Star",
    "rarity": "common",
    "points": 13,
    "minDepth": 8,
    "weight": 31
  },
  {
    "id": "urchin",
    "emoji": "\ud83e\udd94",
    "name": "Sea Urchin",
    "rarity": "common",
    "points": 13,
    "minDepth": 9,
    "weight": 31
  },
  {
    "id": "anemone",
    "emoji": "\ud83c\udf38",
    "name": "Magnificent Anemone",
    "rarity": "common",
    "points": 13,
    "minDepth": 9,
    "weight": 31
  },
  {
    "id": "pistolshrimp",
    "emoji": "\ud83e\udd90",
    "name": "Pistol Shrimp",
    "rarity": "common",
    "points": 14,
    "minDepth": 10,
    "weight": 30
  },
  {
    "id": "bluetang",
    "emoji": "\ud83d\udc1f",
    "name": "Blue Tang",
    "rarity": "common",
    "points": 14,
    "minDepth": 10,
    "weight": 30
  },
  {
    "id": "yellowtail",
    "emoji": "\ud83d\udc1f",
    "name": "Yellowtail Snapper",
    "rarity": "common",
    "points": 14,
    "minDepth": 11,
    "weight": 30
  },
  {
    "id": "sergeant",
    "emoji": "\ud83d\udc1f",
    "name": "Sergeant Major",
    "rarity": "common",
    "points": 15,
    "minDepth": 12,
    "weight": 29
  },
  {
    "id": "mullet",
    "emoji": "\ud83d\udc1f",
    "name": "Striped Mullet",
    "rarity": "common",
    "points": 15,
    "minDepth": 12,
    "weight": 29
  },
  {
    "id": "sanddollar",
    "emoji": "\ud83e\ude99",
    "name": "Sand Dollar",
    "rarity": "common",
    "points": 15,
    "minDepth": 13,
    "weight": 29
  },
  {
    "id": "cucumber",
    "emoji": "\ud83e\udd52",
    "name": "Sea Cucumber",
    "rarity": "common",
    "points": 16,
    "minDepth": 13,
    "weight": 28
  },
  {
    "id": "fireworm",
    "emoji": "\ud83e\udeb1",
    "name": "Fireworm",
    "rarity": "common",
    "points": 16,
    "minDepth": 14,
    "weight": 28
  },
  {
    "id": "jelly",
    "emoji": "\ud83e\udebc",
    "name": "Moon Jelly",
    "rarity": "uncommon",
    "points": 22,
    "minDepth": 15,
    "weight": 24
  },
  {
    "id": "seal",
    "emoji": "\ud83e\uddad",
    "name": "Harbor Seal",
    "rarity": "uncommon",
    "points": 23,
    "minDepth": 18,
    "weight": 24
  },
  {
    "id": "turtle",
    "emoji": "\ud83d\udc22",
    "name": "Sea Turtle",
    "rarity": "uncommon",
    "points": 24,
    "minDepth": 20,
    "weight": 23
  },
  {
    "id": "dolphin",
    "emoji": "\ud83d\udc2c",
    "name": "Dolphin",
    "rarity": "uncommon",
    "points": 25,
    "minDepth": 23,
    "weight": 23
  },
  {
    "id": "octopus",
    "emoji": "\ud83d\udc19",
    "name": "Octopus",
    "rarity": "uncommon",
    "points": 26,
    "minDepth": 26,
    "weight": 22
  },
  {
    "id": "lobster",
    "emoji": "\ud83e\udd9e",
    "name": "Spiny Lobster",
    "rarity": "uncommon",
    "points": 27,
    "minDepth": 28,
    "weight": 22
  },
  {
    "id": "lionfish",
    "emoji": "\ud83d\udc21",
    "name": "Lionfish",
    "rarity": "uncommon",
    "points": 28,
    "minDepth": 31,
    "weight": 22
  },
  {
    "id": "stingray",
    "emoji": "\ud83d\udc1f",
    "name": "Southern Stingray",
    "rarity": "uncommon",
    "points": 28,
    "minDepth": 34,
    "weight": 21
  },
  {
    "id": "manta",
    "emoji": "\ud83d\udc1f",
    "name": "Manta Ray",
    "rarity": "uncommon",
    "points": 29,
    "minDepth": 36,
    "weight": 21
  },
  {
    "id": "barracuda",
    "emoji": "\ud83d\udc1f",
    "name": "Barracuda",
    "rarity": "uncommon",
    "points": 30,
    "minDepth": 39,
    "weight": 21
  },
  {
    "id": "grouper",
    "emoji": "\ud83d\udc1f",
    "name": "Nassau Grouper",
    "rarity": "uncommon",
    "points": 31,
    "minDepth": 42,
    "weight": 20
  },
  {
    "id": "snapper",
    "emoji": "\ud83d\udc1f",
    "name": "Red Snapper",
    "rarity": "uncommon",
    "points": 32,
    "minDepth": 44,
    "weight": 20
  },
  {
    "id": "triggerfish",
    "emoji": "\ud83d\udc21",
    "name": "Picasso Triggerfish",
    "rarity": "uncommon",
    "points": 33,
    "minDepth": 47,
    "weight": 20
  },
  {
    "id": "boxfish",
    "emoji": "\ud83d\udc21",
    "name": "Boxfish",
    "rarity": "uncommon",
    "points": 34,
    "minDepth": 50,
    "weight": 19
  },
  {
    "id": "nautilus",
    "emoji": "\ud83d\udc1a",
    "name": "Chambered Nautilus",
    "rarity": "uncommon",
    "points": 35,
    "minDepth": 52,
    "weight": 19
  },
  {
    "id": "cuttlefish",
    "emoji": "\ud83e\udd91",
    "name": "Cuttlefish",
    "rarity": "uncommon",
    "points": 36,
    "minDepth": 55,
    "weight": 18
  },
  {
    "id": "sealion",
    "emoji": "\ud83e\uddad",
    "name": "Sea Lion",
    "rarity": "uncommon",
    "points": 37,
    "minDepth": 58,
    "weight": 18
  },
  {
    "id": "manatee",
    "emoji": "\ud83d\udc0b",
    "name": "Manatee",
    "rarity": "uncommon",
    "points": 38,
    "minDepth": 60,
    "weight": 18
  },
  {
    "id": "dugong",
    "emoji": "\ud83d\udc0b",
    "name": "Dugong",
    "rarity": "uncommon",
    "points": 38,
    "minDepth": 63,
    "weight": 17
  },
  {
    "id": "seakrait",
    "emoji": "\ud83d\udc0d",
    "name": "Banded Sea Krait",
    "rarity": "uncommon",
    "points": 39,
    "minDepth": 66,
    "weight": 17
  },
  {
    "id": "bonnethead",
    "emoji": "\ud83e\udd88",
    "name": "Bonnethead Shark",
    "rarity": "uncommon",
    "points": 40,
    "minDepth": 68,
    "weight": 16
  },
  {
    "id": "nurseshark",
    "emoji": "\ud83e\udd88",
    "name": "Nurse Shark",
    "rarity": "uncommon",
    "points": 41,
    "minDepth": 71,
    "weight": 16
  },
  {
    "id": "wolfeel",
    "emoji": "\ud83d\udc0d",
    "name": "Wolf Eel",
    "rarity": "uncommon",
    "points": 42,
    "minDepth": 74,
    "weight": 16
  },
  {
    "id": "sunfish",
    "emoji": "\ud83d\udc1f",
    "name": "Ocean Sunfish",
    "rarity": "uncommon",
    "points": 43,
    "minDepth": 76,
    "weight": 15
  },
  {
    "id": "flyingfish",
    "emoji": "\ud83d\udc1f",
    "name": "Flying Fish",
    "rarity": "uncommon",
    "points": 44,
    "minDepth": 79,
    "weight": 15
  },
  {
    "id": "ray",
    "emoji": "\ud83d\udc21",
    "name": "Pufferfish",
    "rarity": "rare",
    "points": 50,
    "minDepth": 45,
    "weight": 12
  },
  {
    "id": "eel",
    "emoji": "\ud83d\udc0d",
    "name": "Moray Eel",
    "rarity": "rare",
    "points": 52,
    "minDepth": 54,
    "weight": 12
  },
  {
    "id": "shark",
    "emoji": "\ud83e\udd88",
    "name": "Reef Shark",
    "rarity": "rare",
    "points": 54,
    "minDepth": 62,
    "weight": 11
  },
  {
    "id": "angler",
    "emoji": "\ud83d\udc1f",
    "name": "Anglerfish",
    "rarity": "rare",
    "points": 56,
    "minDepth": 71,
    "weight": 11
  },
  {
    "id": "viperfish",
    "emoji": "\ud83d\udc09",
    "name": "Viperfish",
    "rarity": "rare",
    "points": 58,
    "minDepth": 79,
    "weight": 11
  },
  {
    "id": "blobfish",
    "emoji": "\ud83e\udee0",
    "name": "Blobfish",
    "rarity": "rare",
    "points": 60,
    "minDepth": 88,
    "weight": 11
  },
  {
    "id": "eagleray",
    "emoji": "\ud83d\udc1f",
    "name": "Eagle Ray",
    "rarity": "rare",
    "points": 62,
    "minDepth": 96,
    "weight": 10
  },
  {
    "id": "thresher",
    "emoji": "\ud83e\udd88",
    "name": "Thresher Shark",
    "rarity": "rare",
    "points": 64,
    "minDepth": 105,
    "weight": 10
  },
  {
    "id": "hammerhead",
    "emoji": "\ud83e\udd88",
    "name": "Hammerhead Shark",
    "rarity": "rare",
    "points": 66,
    "minDepth": 113,
    "weight": 10
  },
  {
    "id": "whaleshark",
    "emoji": "\ud83e\udd88",
    "name": "Whale Shark",
    "rarity": "rare",
    "points": 68,
    "minDepth": 122,
    "weight": 9
  },
  {
    "id": "tigershark",
    "emoji": "\ud83e\udd88",
    "name": "Tiger Shark",
    "rarity": "rare",
    "points": 70,
    "minDepth": 130,
    "weight": 9
  },
  {
    "id": "oarfish",
    "emoji": "\ud83d\udc1f",
    "name": "Oarfish",
    "rarity": "rare",
    "points": 72,
    "minDepth": 139,
    "weight": 9
  },
  {
    "id": "gulper",
    "emoji": "\ud83d\udc0d",
    "name": "Gulper Eel",
    "rarity": "rare",
    "points": 74,
    "minDepth": 148,
    "weight": 8
  },
  {
    "id": "dragonfish",
    "emoji": "\ud83d\udc1f",
    "name": "Black Dragonfish",
    "rarity": "rare",
    "points": 76,
    "minDepth": 156,
    "weight": 8
  },
  {
    "id": "fangtooth",
    "emoji": "\ud83d\udc1f",
    "name": "Fangtooth",
    "rarity": "rare",
    "points": 78,
    "minDepth": 165,
    "weight": 8
  },
  {
    "id": "atolla",
    "emoji": "\ud83e\udebc",
    "name": "Atolla Jelly",
    "rarity": "rare",
    "points": 80,
    "minDepth": 173,
    "weight": 8
  },
  {
    "id": "dumbo",
    "emoji": "\ud83d\udc19",
    "name": "Dumbo Octopus",
    "rarity": "rare",
    "points": 82,
    "minDepth": 182,
    "weight": 7
  },
  {
    "id": "goblin",
    "emoji": "\ud83e\udd88",
    "name": "Goblin Shark",
    "rarity": "rare",
    "points": 84,
    "minDepth": 190,
    "weight": 7
  },
  {
    "id": "frilled",
    "emoji": "\ud83e\udd88",
    "name": "Frilled Shark",
    "rarity": "rare",
    "points": 86,
    "minDepth": 199,
    "weight": 7
  },
  {
    "id": "sixgill",
    "emoji": "\ud83e\udd88",
    "name": "Sixgill Shark",
    "rarity": "rare",
    "points": 88,
    "minDepth": 207,
    "weight": 6
  },
  {
    "id": "barreleye",
    "emoji": "\ud83d\udc1f",
    "name": "Barreleye",
    "rarity": "rare",
    "points": 90,
    "minDepth": 216,
    "weight": 6
  },
  {
    "id": "hatchetfish",
    "emoji": "\ud83d\udc1f",
    "name": "Hatchetfish",
    "rarity": "rare",
    "points": 92,
    "minDepth": 224,
    "weight": 6
  },
  {
    "id": "loosejaw",
    "emoji": "\ud83d\udc1f",
    "name": "Stoplight Loosejaw",
    "rarity": "rare",
    "points": 94,
    "minDepth": 233,
    "weight": 6
  },
  {
    "id": "deeplobster",
    "emoji": "\ud83e\udd9e",
    "name": "Deep-sea Lobster",
    "rarity": "rare",
    "points": 96,
    "minDepth": 241,
    "weight": 5
  },
  {
    "id": "lanternfish",
    "emoji": "\ud83d\udc1f",
    "name": "Lanternfish",
    "rarity": "rare",
    "points": 98,
    "minDepth": 250,
    "weight": 5
  },
  {
    "id": "squid",
    "emoji": "\ud83e\udd91",
    "name": "Giant Squid",
    "rarity": "legendary",
    "points": 120,
    "minDepth": 100,
    "weight": 5
  },
  {
    "id": "whale",
    "emoji": "\ud83d\udc0b",
    "name": "Blue Whale",
    "rarity": "legendary",
    "points": 128,
    "minDepth": 127,
    "weight": 5
  },
  {
    "id": "coelacanth",
    "emoji": "\ud83d\udc1f",
    "name": "Coelacanth",
    "rarity": "legendary",
    "points": 135,
    "minDepth": 154,
    "weight": 5
  },
  {
    "id": "vampire",
    "emoji": "\ud83e\udd91",
    "name": "Vampire Squid",
    "rarity": "legendary",
    "points": 142,
    "minDepth": 181,
    "weight": 4
  },
  {
    "id": "leviathan",
    "emoji": "\ud83d\udc0b",
    "name": "Abyssal Leviathan",
    "rarity": "legendary",
    "points": 150,
    "minDepth": 208,
    "weight": 4
  },
  {
    "id": "spermwhale",
    "emoji": "\ud83d\udc0b",
    "name": "Sperm Whale",
    "rarity": "legendary",
    "points": 158,
    "minDepth": 235,
    "weight": 4
  },
  {
    "id": "orca",
    "emoji": "\ud83d\udc0b",
    "name": "Orca",
    "rarity": "legendary",
    "points": 165,
    "minDepth": 262,
    "weight": 4
  },
  {
    "id": "humpback",
    "emoji": "\ud83d\udc0b",
    "name": "Humpback Whale",
    "rarity": "legendary",
    "points": 172,
    "minDepth": 290,
    "weight": 4
  },
  {
    "id": "narwhal",
    "emoji": "\ud83e\udd84",
    "name": "Narwhal",
    "rarity": "legendary",
    "points": 180,
    "minDepth": 317,
    "weight": 4
  },
  {
    "id": "beluga",
    "emoji": "\ud83d\udc0b",
    "name": "Beluga",
    "rarity": "legendary",
    "points": 188,
    "minDepth": 344,
    "weight": 4
  },
  {
    "id": "colossal",
    "emoji": "\ud83e\udd91",
    "name": "Colossal Squid",
    "rarity": "legendary",
    "points": 195,
    "minDepth": 371,
    "weight": 3
  },
  {
    "id": "gpo",
    "emoji": "\ud83d\udc19",
    "name": "Giant Pacific Octopus",
    "rarity": "legendary",
    "points": 202,
    "minDepth": 398,
    "weight": 3
  },
  {
    "id": "megamouth",
    "emoji": "\ud83e\udd88",
    "name": "Megamouth Shark",
    "rarity": "legendary",
    "points": 210,
    "minDepth": 425,
    "weight": 3
  },
  {
    "id": "greenland",
    "emoji": "\ud83e\udd88",
    "name": "Greenland Shark",
    "rarity": "legendary",
    "points": 218,
    "minDepth": 452,
    "weight": 3
  },
  {
    "id": "isopod",
    "emoji": "\ud83d\udc1b",
    "name": "Giant Isopod",
    "rarity": "legendary",
    "points": 225,
    "minDepth": 479,
    "weight": 3
  },
  {
    "id": "spidercrab",
    "emoji": "\ud83e\udd80",
    "name": "Japanese Spider Crab",
    "rarity": "legendary",
    "points": 232,
    "minDepth": 506,
    "weight": 2
  },
  {
    "id": "yeticrab",
    "emoji": "\ud83e\udd80",
    "name": "Yeti Crab",
    "rarity": "legendary",
    "points": 240,
    "minDepth": 533,
    "weight": 2
  },
  {
    "id": "stygiomedusa",
    "emoji": "\ud83e\udebc",
    "name": "Stygiomedusa",
    "rarity": "legendary",
    "points": 248,
    "minDepth": 560,
    "weight": 2
  },
  {
    "id": "snailfish",
    "emoji": "\ud83d\udc1f",
    "name": "Mariana Snailfish",
    "rarity": "legendary",
    "points": 255,
    "minDepth": 588,
    "weight": 2
  },
  {
    "id": "glasssponge",
    "emoji": "\ud83e\uddfd",
    "name": "Glass Sponge",
    "rarity": "legendary",
    "points": 262,
    "minDepth": 615,
    "weight": 2
  },
  {
    "id": "tubeworm",
    "emoji": "\ud83e\udeb1",
    "name": "Giant Tube Worm",
    "rarity": "legendary",
    "points": 270,
    "minDepth": 642,
    "weight": 2
  },
  {
    "id": "swallower",
    "emoji": "\ud83d\udc1f",
    "name": "Black Swallower",
    "rarity": "legendary",
    "points": 278,
    "minDepth": 669,
    "weight": 2
  },
  {
    "id": "tripod",
    "emoji": "\ud83d\udc1f",
    "name": "Tripod Fish",
    "rarity": "legendary",
    "points": 285,
    "minDepth": 696,
    "weight": 1
  },
  {
    "id": "kraken",
    "emoji": "\ud83d\udc19",
    "name": "Midnight Kraken",
    "rarity": "legendary",
    "points": 292,
    "minDepth": 723,
    "weight": 1
  },
  {
    "id": "wyrm",
    "emoji": "\ud83d\udc09",
    "name": "Hadal Wyrm",
    "rarity": "legendary",
    "points": 300,
    "minDepth": 750,
    "weight": 1
  }
];

const CREATURE_SWIM = {
  "_default": {
    "style": "cruise",
    "speed": 28,
    "vert": 3,
    "wobble": 10,
    "phaseSpd": 2,
    "depthRange": 4
  },
  "sardine": {
    "style": "school",
    "speed": 52,
    "vert": 5,
    "wobble": 12,
    "phaseSpd": 3.5,
    "depthRange": 6
  },
  "shrimp": {
    "style": "dart",
    "speed": 38,
    "vert": 10,
    "phaseSpd": 4.8,
    "depthRange": 3
  },
  "clownfish": {
    "style": "hover",
    "speed": 22,
    "vert": 4,
    "wobble": 8,
    "phaseSpd": 2.8,
    "depthRange": 2
  },
  "shell": {
    "style": "settled",
    "phaseSpd": 0.35,
    "depthRange": 0.35,
    "noFlip": true
  },
  "crab": {
    "style": "bottom",
    "speed": 14,
    "phaseSpd": 2.2,
    "depthRange": 2
  },
  "anchovy": {
    "style": "school",
    "speed": 52,
    "vert": 5,
    "wobble": 12,
    "phaseSpd": 3.5,
    "depthRange": 6
  },
  "silverside": {
    "style": "school",
    "speed": 52,
    "vert": 5,
    "wobble": 12,
    "phaseSpd": 3.5,
    "depthRange": 6
  },
  "damselfish": {
    "style": "cruise",
    "speed": 20,
    "vert": 4,
    "wobble": 6,
    "phaseSpd": 1.4,
    "depthRange": 9
  },
  "parrotfish": {
    "style": "cruise",
    "speed": 20,
    "vert": 4,
    "wobble": 6,
    "phaseSpd": 1.4,
    "depthRange": 9
  },
  "butterflyfish": {
    "style": "hover",
    "speed": 22,
    "vert": 4,
    "wobble": 8,
    "phaseSpd": 2.8,
    "depthRange": 2
  },
  "blenny": {
    "style": "cruise",
    "speed": 20,
    "vert": 4,
    "wobble": 6,
    "phaseSpd": 1.4,
    "depthRange": 9
  },
  "goby": {
    "style": "cruise",
    "speed": 20,
    "vert": 4,
    "wobble": 6,
    "phaseSpd": 1.4,
    "depthRange": 9
  },
  "seahorse": {
    "style": "hover",
    "speed": 22,
    "vert": 4,
    "wobble": 8,
    "phaseSpd": 2.8,
    "depthRange": 2
  },
  "pipefish": {
    "style": "cruise",
    "speed": 20,
    "vert": 4,
    "wobble": 6,
    "phaseSpd": 1.4,
    "depthRange": 9
  },
  "starfish": {
    "style": "settled",
    "phaseSpd": 0.35,
    "depthRange": 0.35,
    "noFlip": true
  },
  "urchin": {
    "style": "settled",
    "phaseSpd": 0.35,
    "depthRange": 0.35,
    "noFlip": true
  },
  "anemone": {
    "style": "settled",
    "phaseSpd": 0.35,
    "depthRange": 0.35,
    "noFlip": true
  },
  "pistolshrimp": {
    "style": "dart",
    "speed": 38,
    "vert": 10,
    "phaseSpd": 4.8,
    "depthRange": 3
  },
  "bluetang": {
    "style": "hover",
    "speed": 22,
    "vert": 4,
    "wobble": 8,
    "phaseSpd": 2.8,
    "depthRange": 2
  },
  "yellowtail": {
    "style": "cruise",
    "speed": 20,
    "vert": 4,
    "wobble": 6,
    "phaseSpd": 1.4,
    "depthRange": 9
  },
  "sergeant": {
    "style": "school",
    "speed": 52,
    "vert": 5,
    "wobble": 12,
    "phaseSpd": 3.5,
    "depthRange": 6
  },
  "mullet": {
    "style": "school",
    "speed": 52,
    "vert": 5,
    "wobble": 12,
    "phaseSpd": 3.5,
    "depthRange": 6
  },
  "sanddollar": {
    "style": "settled",
    "phaseSpd": 0.35,
    "depthRange": 0.35,
    "noFlip": true
  },
  "cucumber": {
    "style": "bottom",
    "speed": 14,
    "phaseSpd": 2.2,
    "depthRange": 2
  },
  "fireworm": {
    "style": "bottom",
    "speed": 14,
    "phaseSpd": 2.2,
    "depthRange": 2
  },
  "jelly": {
    "style": "drift",
    "speed": 14,
    "vert": 9,
    "drift": 7,
    "phaseSpd": 1.3,
    "depthRange": 9
  },
  "seal": {
    "style": "fast_cruise",
    "speed": 44,
    "vert": 7,
    "wobble": 10,
    "phaseSpd": 2.4,
    "depthRange": 11
  },
  "turtle": {
    "style": "cruise",
    "speed": 20,
    "vert": 4,
    "wobble": 6,
    "phaseSpd": 1.4,
    "depthRange": 9
  },
  "dolphin": {
    "style": "fast_cruise",
    "speed": 44,
    "vert": 7,
    "wobble": 10,
    "phaseSpd": 2.4,
    "depthRange": 11
  },
  "octopus": {
    "style": "jet",
    "speed": 30,
    "vert": 10,
    "phaseSpd": 1.55,
    "depthRange": 7
  },
  "lobster": {
    "style": "bottom",
    "speed": 11,
    "phaseSpd": 1.7,
    "depthRange": 3
  },
  "lionfish": {
    "style": "hover",
    "speed": 22,
    "vert": 4,
    "wobble": 8,
    "phaseSpd": 2.8,
    "depthRange": 2
  },
  "stingray": {
    "style": "glide",
    "speed": 24,
    "vert": 7,
    "phaseSpd": 0.85,
    "depthRange": 22
  },
  "manta": {
    "style": "glide",
    "speed": 24,
    "vert": 7,
    "phaseSpd": 0.85,
    "depthRange": 22
  },
  "barracuda": {
    "style": "fast_cruise",
    "speed": 44,
    "vert": 7,
    "wobble": 10,
    "phaseSpd": 2.4,
    "depthRange": 11
  },
  "grouper": {
    "style": "stalk",
    "speed": 18,
    "wobble": 20,
    "vert": 3,
    "phaseSpd": 2.1,
    "depthRange": 4
  },
  "snapper": {
    "style": "cruise",
    "speed": 20,
    "vert": 4,
    "wobble": 6,
    "phaseSpd": 1.4,
    "depthRange": 9
  },
  "triggerfish": {
    "style": "hover",
    "speed": 22,
    "vert": 4,
    "wobble": 8,
    "phaseSpd": 2.8,
    "depthRange": 2
  },
  "boxfish": {
    "style": "hover",
    "speed": 22,
    "vert": 4,
    "wobble": 8,
    "phaseSpd": 2.8,
    "depthRange": 2
  },
  "nautilus": {
    "style": "cruise",
    "speed": 20,
    "vert": 4,
    "wobble": 6,
    "phaseSpd": 1.4,
    "depthRange": 9
  },
  "cuttlefish": {
    "style": "jet",
    "speed": 30,
    "vert": 10,
    "phaseSpd": 1.55,
    "depthRange": 7
  },
  "sealion": {
    "style": "fast_cruise",
    "speed": 44,
    "vert": 7,
    "wobble": 10,
    "phaseSpd": 2.4,
    "depthRange": 11
  },
  "manatee": {
    "style": "cruise",
    "speed": 20,
    "vert": 4,
    "wobble": 6,
    "phaseSpd": 1.4,
    "depthRange": 9
  },
  "dugong": {
    "style": "cruise",
    "speed": 20,
    "vert": 4,
    "wobble": 6,
    "phaseSpd": 1.4,
    "depthRange": 9
  },
  "seakrait": {
    "style": "cruise",
    "speed": 20,
    "vert": 4,
    "wobble": 6,
    "phaseSpd": 1.4,
    "depthRange": 9
  },
  "bonnethead": {
    "style": "patrol",
    "speed": 40,
    "vert": 6,
    "wobble": 5,
    "phaseSpd": 1.9,
    "depthRange": 14
  },
  "nurseshark": {
    "style": "patrol",
    "speed": 40,
    "vert": 6,
    "wobble": 5,
    "phaseSpd": 1.9,
    "depthRange": 14
  },
  "wolfeel": {
    "style": "stalk",
    "speed": 18,
    "wobble": 20,
    "vert": 3,
    "phaseSpd": 2.1,
    "depthRange": 4
  },
  "sunfish": {
    "style": "glide",
    "speed": 24,
    "vert": 7,
    "phaseSpd": 0.85,
    "depthRange": 22
  },
  "flyingfish": {
    "style": "dart",
    "speed": 38,
    "vert": 10,
    "phaseSpd": 4.8,
    "depthRange": 3
  },
  "ray": {
    "style": "hover",
    "speed": 16,
    "vert": 5,
    "wobble": 11,
    "phaseSpd": 1.6,
    "depthRange": 5
  },
  "eel": {
    "style": "stalk",
    "speed": 18,
    "wobble": 20,
    "vert": 3,
    "phaseSpd": 2.1,
    "depthRange": 4
  },
  "shark": {
    "style": "patrol",
    "speed": 40,
    "vert": 6,
    "wobble": 5,
    "phaseSpd": 1.9,
    "depthRange": 14
  },
  "angler": {
    "style": "stalk",
    "speed": 7,
    "wobble": 5,
    "vert": 2,
    "phaseSpd": 1,
    "depthRange": 3
  },
  "viperfish": {
    "style": "dart",
    "speed": 32,
    "vert": 9,
    "phaseSpd": 3.1,
    "depthRange": 9
  },
  "blobfish": {
    "style": "drift",
    "speed": 7,
    "vert": 2.5,
    "drift": 3,
    "phaseSpd": 0.75,
    "depthRange": 4
  },
  "eagleray": {
    "style": "glide",
    "speed": 24,
    "vert": 7,
    "phaseSpd": 0.85,
    "depthRange": 22
  },
  "thresher": {
    "style": "patrol",
    "speed": 40,
    "vert": 6,
    "wobble": 5,
    "phaseSpd": 1.9,
    "depthRange": 14
  },
  "hammerhead": {
    "style": "patrol",
    "speed": 40,
    "vert": 6,
    "wobble": 5,
    "phaseSpd": 1.9,
    "depthRange": 14
  },
  "whaleshark": {
    "style": "glide",
    "speed": 24,
    "vert": 7,
    "phaseSpd": 0.85,
    "depthRange": 22
  },
  "tigershark": {
    "style": "patrol",
    "speed": 40,
    "vert": 6,
    "wobble": 5,
    "phaseSpd": 1.9,
    "depthRange": 14
  },
  "oarfish": {
    "style": "glide",
    "speed": 24,
    "vert": 7,
    "phaseSpd": 0.85,
    "depthRange": 22
  },
  "gulper": {
    "style": "stalk",
    "speed": 18,
    "wobble": 20,
    "vert": 3,
    "phaseSpd": 2.1,
    "depthRange": 4
  },
  "dragonfish": {
    "style": "dart",
    "speed": 38,
    "vert": 10,
    "phaseSpd": 4.8,
    "depthRange": 3
  },
  "fangtooth": {
    "style": "dart",
    "speed": 38,
    "vert": 10,
    "phaseSpd": 4.8,
    "depthRange": 3
  },
  "atolla": {
    "style": "drift",
    "speed": 14,
    "vert": 9,
    "drift": 7,
    "phaseSpd": 1.3,
    "depthRange": 9
  },
  "dumbo": {
    "style": "drift",
    "speed": 14,
    "vert": 9,
    "drift": 7,
    "phaseSpd": 1.3,
    "depthRange": 9
  },
  "goblin": {
    "style": "stalk",
    "speed": 18,
    "wobble": 20,
    "vert": 3,
    "phaseSpd": 2.1,
    "depthRange": 4
  },
  "frilled": {
    "style": "stalk",
    "speed": 18,
    "wobble": 20,
    "vert": 3,
    "phaseSpd": 2.1,
    "depthRange": 4
  },
  "sixgill": {
    "style": "patrol",
    "speed": 40,
    "vert": 6,
    "wobble": 5,
    "phaseSpd": 1.9,
    "depthRange": 14
  },
  "barreleye": {
    "style": "drift",
    "speed": 14,
    "vert": 9,
    "drift": 7,
    "phaseSpd": 1.3,
    "depthRange": 9
  },
  "hatchetfish": {
    "style": "drift",
    "speed": 14,
    "vert": 9,
    "drift": 7,
    "phaseSpd": 1.3,
    "depthRange": 9
  },
  "loosejaw": {
    "style": "dart",
    "speed": 38,
    "vert": 10,
    "phaseSpd": 4.8,
    "depthRange": 3
  },
  "deeplobster": {
    "style": "bottom",
    "speed": 14,
    "phaseSpd": 2.2,
    "depthRange": 2
  },
  "lanternfish": {
    "style": "school",
    "speed": 52,
    "vert": 5,
    "wobble": 12,
    "phaseSpd": 3.5,
    "depthRange": 6
  },
  "squid": {
    "style": "jet",
    "speed": 34,
    "vert": 13,
    "phaseSpd": 1.85,
    "depthRange": 11
  },
  "whale": {
    "style": "glide",
    "speed": 24,
    "vert": 7,
    "phaseSpd": 0.85,
    "depthRange": 22
  },
  "coelacanth": {
    "style": "glide",
    "speed": 13,
    "vert": 4,
    "phaseSpd": 0.65,
    "depthRange": 9
  },
  "vampire": {
    "style": "drift",
    "speed": 11,
    "vert": 6,
    "drift": 5,
    "phaseSpd": 0.95,
    "depthRange": 13
  },
  "leviathan": {
    "style": "glide",
    "speed": 16,
    "vert": 9,
    "phaseSpd": 0.5,
    "depthRange": 28
  },
  "spermwhale": {
    "style": "glide",
    "speed": 24,
    "vert": 7,
    "phaseSpd": 0.85,
    "depthRange": 22
  },
  "orca": {
    "style": "fast_cruise",
    "speed": 44,
    "vert": 7,
    "wobble": 10,
    "phaseSpd": 2.4,
    "depthRange": 11
  },
  "humpback": {
    "style": "glide",
    "speed": 24,
    "vert": 7,
    "phaseSpd": 0.85,
    "depthRange": 22
  },
  "narwhal": {
    "style": "cruise",
    "speed": 20,
    "vert": 4,
    "wobble": 6,
    "phaseSpd": 1.4,
    "depthRange": 9
  },
  "beluga": {
    "style": "cruise",
    "speed": 20,
    "vert": 4,
    "wobble": 6,
    "phaseSpd": 1.4,
    "depthRange": 9
  },
  "colossal": {
    "style": "jet",
    "speed": 30,
    "vert": 10,
    "phaseSpd": 1.55,
    "depthRange": 7
  },
  "gpo": {
    "style": "jet",
    "speed": 30,
    "vert": 10,
    "phaseSpd": 1.55,
    "depthRange": 7
  },
  "megamouth": {
    "style": "glide",
    "speed": 24,
    "vert": 7,
    "phaseSpd": 0.85,
    "depthRange": 22
  },
  "greenland": {
    "style": "glide",
    "speed": 24,
    "vert": 7,
    "phaseSpd": 0.85,
    "depthRange": 22
  },
  "isopod": {
    "style": "bottom",
    "speed": 14,
    "phaseSpd": 2.2,
    "depthRange": 2
  },
  "spidercrab": {
    "style": "bottom",
    "speed": 14,
    "phaseSpd": 2.2,
    "depthRange": 2
  },
  "yeticrab": {
    "style": "bottom",
    "speed": 14,
    "phaseSpd": 2.2,
    "depthRange": 2
  },
  "stygiomedusa": {
    "style": "drift",
    "speed": 14,
    "vert": 9,
    "drift": 7,
    "phaseSpd": 1.3,
    "depthRange": 9
  },
  "snailfish": {
    "style": "drift",
    "speed": 14,
    "vert": 9,
    "drift": 7,
    "phaseSpd": 1.3,
    "depthRange": 9
  },
  "glasssponge": {
    "style": "settled",
    "phaseSpd": 0.35,
    "depthRange": 0.35,
    "noFlip": true
  },
  "tubeworm": {
    "style": "settled",
    "phaseSpd": 0.35,
    "depthRange": 0.35,
    "noFlip": true
  },
  "swallower": {
    "style": "stalk",
    "speed": 18,
    "wobble": 20,
    "vert": 3,
    "phaseSpd": 2.1,
    "depthRange": 4
  },
  "tripod": {
    "style": "settled",
    "phaseSpd": 0.35,
    "depthRange": 0.35,
    "noFlip": true
  },
  "kraken": {
    "style": "glide",
    "speed": 18,
    "vert": 10,
    "phaseSpd": 0.45,
    "depthRange": 30
  },
  "wyrm": {
    "style": "glide",
    "speed": 14,
    "vert": 11,
    "phaseSpd": 0.4,
    "depthRange": 32
  }
};
